In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("All libraries imported successfully!")

All libraries imported successfully!

In [2]:
df = pd.read_csv('../data/SampleSuperstore.csv', encoding='latin1')
print("Shape:", df.shape)
print("\nFirst 5 rows:")
df.head()

Shape: (9994, 13)

First 5 rows:

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [3]:
print("Column Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nBasic Statistics:")
df.describe()

Column Names:
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount', 'Profit']

Data Types:
Ship Mode        object
Segment          object
Country          object
City             object
State            object
Postal Code       int64
Region           object
Category         object
Sub-Category     object
Sales           float64
Quantity          int64
Discount        float64
Profit          float64
dtype: object

Basic Statistics:

        Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

In [4]:
print("Missing Values in each column:")
print(df.isnull().sum())

print("\nTotal Duplicate Rows:", df.duplicated().sum())

print("\nTotal Rows:", len(df))

Missing Values in each column:
Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

Total Duplicate Rows: 17

Total Rows: 9994

In [5]:
# Remove duplicate rows
df = df.drop_duplicates()

print("Rows after removing duplicates:", len(df))
print("Duplicates removed:", 9994 - len(df))

Rows after removing duplicates: 9977
Duplicates removed: 17

In [6]:
# Profit Margin per order
df['Profit_Margin'] = round((df['Profit'] / df['Sales']) * 100, 2)

# Discount Bands (same as our SQL query)
df['Discount_Band'] = pd.cut(
    df['Discount'],
    bins=[-1, 0, 0.20, 0.40, 1.0],
    labels=['No Discount', 'Low (1-20%)', 'Medium (21-40%)', 'High (41%+)']
)

print("New columns added successfully!")
print(df[['Sales', 'Profit', 'Profit_Margin', 'Discount', 'Discount_Band']].head())

New columns added successfully!
      Sales    Profit  Profit_Margin  Discount Discount_Band
0  261.9600   41.9136          16.00      0.00   No Discount
1  731.9400  219.5820          30.00      0.00   No Discount
2   14.6200    6.8714          47.00      0.00   No Discount
3  957.5775 -383.0310         -40.00      0.45   High (41%+)
4   22.3680    2.5164          11.25      0.20   Low (1-20%)

In [7]:
df.to_csv('../data/superstore_clean.csv', index=False)
print("Cleaned file saved successfully!")

Cleaned file saved successfully!